#
# OrangeFox Recovery build variables for zephyr (GT Neo 3 / Oneplus 10R-Ace)
#

FOX_VARIANT := a15
OF_MAINTAINER := Thundergod Thor
FOX_MAINTAINER_AVATAR := $(DEVICE_PATH)/Maintainer.png
FOX_BUILD_TYPE := Unofficial

FOX_VENDOR_BOOT_RECOVERY := 1
FOX_INSTALLER_VENDOR_BOOT_RAMDISK_INSTALL := 0
FOX_PORTS_INSTALLER := $(DEVICE_PATH)/installer
FOX_VIRTUAL_AB_DEVICE := 1
OF_NO_REFLASH_CURRENT_ORANGEFOX := 1

FOX_RECOVERY_SYSTEM_PARTITION := /dev/block/mapper/system
FOX_RECOVERY_VENDOR_PARTITION := /dev/block/mapper/vendor

FOX_ENABLE_APP_MANAGER := 1
FOX_INSTALLER_DISABLE_AUTOREBOOT := 0
FOX_DELETE_AROMAFM := 1
OF_FLASHLIGHT_ENABLE := 0

FOX_USE_BASH_SHELL := 1
FOX_ASH_IS_BASH := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_LZ4_BINARY := 1
FOX_USE_SED_BINARY := 1
FOX_USE_XZ_UTILS := 1
FOX_USE_ZSTD_BINARY := 1
FOX_USE_NANO_EDITOR := 1
FOX_USE_UPDATED_MAGISKBOOT := 1
FOX_USE_DATE_BINARY := 1

FOX_TARGET_DEVICES := zephyr
TARGET_DEVICE_ALT := zephyr

# Notch / punch-hole camera (top-left, 150x118px)
OF_SCREEN_H := 2412
OF_STATUS_H := 118
OF_STATUS_INDENT_LEFT := 150
OF_STATUS_INDENT_RIGHT := 48
OF_CLOCK_POS := 0
